name: Matrix Configuration

on:
  push:
  workflow_dispatch: 
  
jobs:
    deploy:
      strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-lastet]
          images: [hello-world, alpine]
          exclude:
            - images: alpine
              os: windows-lastet
          include:
            - images: amd64/alpine
              os: ubuntu-20.04
      runs-on: ${{ matrix.os }}
      steps:
          - name: Echo Docker Details Build
            run: docker info

          - name: Run Images
            run: docker run ${{ matrix.images }}