name: Tiggering workflows

on:
  workflow_dispatch: 
  #schedule:
  #  - cron: '*/1 * * * *'
  
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest

            - name: Docker Login
              run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.GITHUB_TOKEN}}

            - name: Docker Publish
              run: echo docker ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
        
    deploy:
        needs: docker
        concurrency:
          group: concurrency-test
          cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: | 
                echo docker run -d -p 8080:80 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
                sleep 600s
